config/routes.rb
Blog::Application.routes.draw do
  resources :articles
  get "home/index"

end

app/models/articles.rb
class Articles < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
	
	def create
  #@article = Article.new(article_params)
 @article = Article.new(params[:article])
  @article.save
  redirect_to @article
end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/new.html.erb
<h1>New Articles</h1>

<%= form_for :article, url: articles_path do |d| %>
  <p>
    <%= d.label :title %><br>
    <%= d.text_field :title %>
  </p>
 
  <p>
    <%= d.label :text %><br>
    <%= d.text_area :text %>
  </p>
 
  <p>
    <%= d.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Hello world, I am keen on learning ruby on rails, May God help me</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>